Add consts to PyUFuncGenericFunction declarations
TEOS-10/GSW-Python pull request #99
Opened 2022-08-28 05:05 UTC by hoodmane

`PyUFuncGenericFunction` has type `void (*)(char **, const npy_intp *, const npy_intp *, void *)`, so `dimensions` and `steps` should be const. Otherwise compiling with `-Wincompatible-function-pointer-types` will fail.

https://app.circleci.com/pipelines/github/hoodmane/pyodide/3783/workflows/3c5fdd0d-baf9-41b7-8dc8-56511ba2fdc0/jobs/45949

2022-08-28 17:57 UTC, efiring requested changes
Thank you, good idea.
https://numpy.org/doc/stable/reference/c-api/ufunc.html#c.PyUFuncGenericFunction shows the order as `int const *x` rather than the presumably equivalent `const int *x`.  Is there a reason you chose the second form rather than matching the docs and ufuncobject.h?

2022-08-28 18:00 UTC, hoodmane commented
No reason. It is indeed probably better to be consistent, I will switch it.

2022-08-28 18:06 UTC, hoodmane commented
Should I squash commits?

2022-08-28 19:46 UTC, efiring approved these changes

2022-08-28 19:47 UTC, merged

2022-08-28 19:48 UTC, efiring commented
I just used the "squash and merge" option of the merge button...
Thank you for the PR.

2022-10-13 18:36 UTC, efiring commented
It turns out this was missing a critical element: the change in the code generator, tools/make_ufuncs.py.
This is fixed by #109.